name: Use secrets and env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: read
  actions: read
  deployments: write

env:
  URL1: 'https://github.com'
  URL2: 'https://docs.github.com'

jobs:
  use-environment-1:
    name: Use environment 1
    runs-on: ubuntu-latest
    # Use conditions to control whether the job is triggered or skipped
    if: ${{github.event_name == 'pull_request'}}
    # An env can be specified per job
    # We can use the variable and expressions in the url field
    # If the env cannt found, it will be created
    
    environment:
      name: Test
      url: ${{ env.URL1 }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Some step using the env
        run: echo "In this step we could for example do the deployment to ${{ env.URL1}}..."

  use-environment-2:
    name: Use environment 2
    runs-on: ubuntu-latest
    # Use conditions to control whether the job is triggered or skipped
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    # An env can be specified per job
    # We can use the variable and expressions in the url field
    # If the env cannt found, it will be created
    
    environment:
      name: Prod
      url: ${{ env.URL2 }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Some step using the env
        run: echo "In this step we could for example do the deployment to ${{ env.URL2}}..."
      # Secrets are redacted in logs
      - name: Echo a secret
        run: echo ${{ secrets.PROD_SECRET}}
